export const STORYLINE = [
  {
    id: 0,
    line: "June 28, 1993: The mayor tells me that 5 of my men are called in. They have not worked together before, nor are they well acquainted, but these select few were handpicked by the mayor to work on a drug runner case to form a task force led by not me, but the mayor. I was shocked. Usually, as the major of the police department, I led the task forces, but it is the mayor afterall, so who was I to say anything?",
    choice: false,
    goto: 1,
  },
  {
    id: 1,
    line: "June 29, 1993: In the morning, I hand the deputy a walkie talkie, telling him to update me about the task on hand. While they investigate the drug case, I stand on guard waiting for updates. After a few hours, the walkie talkie suddenly beeps, transmitting the deputy’s voice. “Major”, the deputy says, updating me on where they investigated and any leads that have been made. After a few minutes, he says, “But the real reason I am updating you now is because...”",
    choice: false,
    goto: 2,
  },
  {
    id: 2,
    line: "“We found a dead body near the University. What should we do?”",
    choice: true,
    ca: "(A) Tell the force to proceed with their initial task",
    cb: "(B) Tell them to investigate the course",
    gotoa: 3,
    gotob: 6,
  },
  {
    id: 3,
    line: 'I instructed the force to proceed with their initial task, knowing the mayor will be unhappy if they leave it untouched. However, the walkie talkie beeps again a few minutes later. “Sir," the deputy states, " we just received a report that another body has been found near the first body. The civilians found a gunshot wound on her face, gagged with a handkerchief. What should we do major?" ',
    choice: true,
    ca: "(A) Continue with initial task",
    cb: "(B) Let justice be served",
    gotoa: 4,
    gotob: 5,
  },
  {
    id: 4,
    line: "I proceeded to order the team to continue with the drug runner case. As time passes, they continuously make leads, and we are able to solve the case. But the mystery of the two bodies forever remains… ",
    choice: false,
    goto: 0,
  },
  {
    id: 5,
    line: "Though this is a digression from the purpose of the force, I order my men to bring the bodies in for an autopsy at the University's morgue hospital. Although the mayor may become unhappy with me, I know what I am doing will serve these two individuals justice. Ten minutes later, I received a transmission from the deputy. “Major, we have brought in the two bodies for an autopsy, but something strange occurred. When we came in, many of the students who were in the building… recognized the bodies?”",
    choice: false,
    goto: 0,
  },
  {
    id: 6,
    line: "I instruct the men to investigate the course with the mayor’s task in the back of my mind. After ten minutes of them carefully examining the body, I got a transmission from the deputy. “Major, after taking a look at the body, we have found two gunshot wounds on both his head and in the back. However, we are still unable to determine who this is or where they came from.”",
    choice: false,
    goto: 7,
  },
  {
    id: 7,
    line: "Ten minutes later, I received another transmission, “Major, we brought the body in for an autopsy at the University’s morgue hospital, but something strange occurred. Around the same time we brought it in, another body that had been found near this one was brought in?”",
    choice: false,
    goto: 0,
  },
];
