export const STORYLINE = [
  {
    id: 0,
    line: "June 28, 1993: The mayor tells me that 5 of my men are called in. They have not worked together before, nor are they well acquainted, but these select few were handpicked by the mayor to work on a drug runner case to form a task force led by not me, but the mayor. I was shocked. Usually, as the major of the police department, I led the task forces, but it is the mayor afterall, so who was I to say anything?",
    choice: false,
    goto: 1,
  },
  {
    id: 1,
    line: "June 29, 1993: In the morning, I hand the deputy a walkie talkie, telling him to update me about the task on hand. While they investigate the drug case, I stand on guard waiting for updates. After a few hours, the walkie talkie suddenly beeps, transmitting the deputy’s voice. “Major”, the deputy says, updating me on where they investigated and any leads that have been made. After a few minutes, he says, “But the real reason I am updating you now is because...”",
    choice: false,
    goto: 2,
  },
  {
    id: 2,
    line: "“We found a dead body near the University. What should we do?”",
    choice: true,
    ca: "(A) Tell the force to proceed with their initial task",
    cb: "(B) Tell them to investigate the course",
    gotoa: 3,
    gotob: 6,
  },
  {
    id: 3,
    line: 'I instructed the force to proceed with their initial task, knowing the mayor will be unhappy if they leave it untouched. However, the walkie talkie beeps again a few minutes later. “Sir," the deputy states, "we just received a report that another body has been found near the first body. The civilians found a gunshot wound on her face, gagged with a handkerchief. What should we do major?" ',
    choice: true,
    ca: "(A) Continue with initial task",
    cb: "(B) Let justice be served",
    gotoa: 4,
    gotob: 5,
  },
  {
    id: 4,
    line: "I proceeded to order the team to continue with the drug runner case. As time passes, they continuously make leads, and we are able to solve the case. But the mystery of the two bodies forever remains… ",
    choice: false,
    goto: 0,
  },
  {
    id: 5,
    line: "Though this is a digression from the purpose of the force, I order my men to bring the bodies in for an autopsy at the University's morgue hospital. Although the mayor may become unhappy with me, I know what I am doing will serve these two individuals justice. Ten minutes later, I received a transmission from the deputy. “Major, we have brought in the two bodies for an autopsy, but something strange occurred. When we came in, many of the students who were in the building… recognized the bodies?”",
    choice: false,
    goto: 8,
  },
  {
    id: 6,
    line: "I instruct the men to investigate the course with the mayor’s task in the back of my mind. After ten minutes of them carefully examining the body, I got a transmission from the deputy. “Major, after taking a look at the body, we have found two gunshot wounds on both his head and in the back. However, we are still unable to determine who this is or where they came from.”",
    choice: false,
    goto: 7,
  },
  {
    id: 7,
    line: "Ten minutes later, I received another transmission, “Major, we brought the body in for an autopsy at the University’s morgue hospital, but something strange occurred. Around the same time we brought it in, another body that had been found near this one was brought in?”",
    choice: false,
    goto: 8,
  },
  {
    id: 8,
    line: "Huh. Interesting. I instructed the detective to come to where I was so we could discuss the details in person. I sat him down and told him to explain the details. He states, “From as far as I’ve heard and seen, the first body is a boy and the second body is a girl. The first body sustained a gunshot to his head and another to his back from a 2-3 feet range. We found his wallet near the University.” He hands the wallet over to me. ",
    choice: false,
    goto: 9,
  },
  {
    id: 9,
    line: "I took out his ID from the wallet. “His name is Alan,” the detective continues. “19, always laughing according to the classmates who knew him.”<br/><br/>“How about the second body?” I asked. <br/><br/>“The second one had sustained a gunshot on the side of her cheek while the gun seemed to be touching her face. The second body also had bodily fluids “flowing out” of her.”",
    choice: false,
    goto: 10,
  },
  {
    id: 10,
    line: "“It’s pretty safe to say that the girl was the target then. Have you guys determined who it is?” I asked. <br/><br/>“Aileen, 21 years old, a student at this university. According to those who knew her, she was a very curious and nice person.” <br/><br/>Huh. Our country keeps failing to protect these children.",
    choice: false,
    goto: 11,
  },
  {
    id: 11,
    line: "The detective continues without me prompting him. “I was thinking that maybe Alan did it.” <br/><br/>I put the wallet down on the table and raised an eyebrow. “Elaborate?”",
    choice: false,
    goto: 12,
  },
  {
    id: 12,
    line: "“Not trying to victim blame, of course. But from those same classmates, we heard that Alan got into a fight with another guy a couple months ago. Alan liked Aileen, but got rejected because Aileen has a boyfriend. He pretended to be understanding and continued being friends. Then when he lost the fight, his ego got hurt, and what do men with hurt ego do? They like to blame it on women, and Alan blamed it on Aileen because she rejected him. Therefore, I think it's pretty safe to say that Alan did it.”",
    choice: false,
    goto: 13,
  },
  {
    id: 13,
    line: "Wow. So he already has a theory.",
    choice: true,
    ca: "(A) His theory seems reasonable",
    cb: "(B) What is this kid saying?",
    gotoa: 14,
    gotob: 15,
  },
  {
    id: 14,
    line: 'Huh, seems reasonable. "Wrap up the case and call it a day".<br/><br/>But is that really the truth?',
    choice: false,
    goto: 0,
  },
];
