export const STORYLINE = [
  {
    id: 0,
    line: "June 28, 1993: The mayor tells me that 5 of my men are called in. They have not worked together before, nor are they well acquainted, but these select few were handpicked by the mayor to work on a drug runner case to form a task force led by not me, but the mayor. I was shocked. Usually, as the major of the police department, I led the task forces, but it is the mayor afterall, so who was I to say anything?",
    choice: false,
    goto: 1,
  },
  {
    id: 1,
    line: "June 29, 1993: In the morning, I hand the deputy a walkie talkie, telling him to update me about the task on hand. While they investigate the drug case, I stand on guard waiting for updates. After a few hours, the walkie talkie suddenly beeps, transmitting the deputy’s voice. “Major”, the deputy says, updating me on where they investigated and any leads that have been made. After a few minutes, he says, “But the real reason I am updating you now is because...”",
    choice: false,
    goto: 2,
  },
  {
    id: 2,
    line: "“We found a dead body near the University. What should we do?”",
    choice: true,
    ca: "(A) Tell the force to proceed with their initial task",
    cb: "(B) Tell them to investigate the course",
    gotoa: 3,
    gotob: 6,
  },
  {
    id: 3,
    line: 'I instructed the force to proceed with their initial task, knowing the mayor will be unhappy if they leave it untouched. However, the walkie talkie beeps again a few minutes later. “Sir," the deputy states, "we just received a report that another body has been found near the first body. The civilians found a gunshot wound on her face, gagged with a handkerchief. What should we do major?" ',
    choice: true,
    ca: "(A) Continue with initial task",
    cb: "(B) Let justice be served",
    gotoa: 4,
    gotob: 5,
  },
  {
    id: 4,
    line: "I proceeded to order the team to continue with the drug runner case. As time passes, they continuously make leads, and we are able to solve the case. But the mystery of the two bodies forever remains… ",
    choice: false,
    goto: 0,
  },
  {
    id: 5,
    line: "Though this is a digression from the purpose of the force, I order my men to bring the bodies in for an autopsy at the University's morgue hospital. Although the mayor may become unhappy with me, I know what I am doing will serve these two individuals justice. Ten minutes later, I received a transmission from the deputy. “Major, we have brought in the two bodies for an autopsy, but something strange occurred. When we came in, many of the students who were in the building… recognized the bodies?”",
    choice: false,
    goto: 8,
  },
  {
    id: 6,
    line: "I instruct the men to investigate the course with the mayor’s task in the back of my mind. After ten minutes of them carefully examining the body, I got a transmission from the deputy. “Major, after taking a look at the body, we have found two gunshot wounds on both his head and in the back. However, we are still unable to determine who this is or where they came from.”",
    choice: false,
    goto: 7,
  },
  {
    id: 7,
    line: "Ten minutes later, I received another transmission, “Major, we brought the body in for an autopsy at the University’s morgue hospital, but something strange occurred. Around the same time we brought it in, another body that had been found near this one was brought in?”",
    choice: false,
    goto: 8,
  },
  {
    id: 8,
    line: "Huh. Interesting. I instructed the deputy to come to where I was so we could discuss the details in person. I sat him down and told him to explain the details. He states, “From as far as I’ve heard and seen, the first body is a boy and the second body is a girl. The first body sustained a gunshot to his head and another to his back from a 2-3 feet range. We found his wallet near the University.” He hands the wallet over to me. ",
    choice: false,
    goto: 9,
  },
  {
    id: 9,
    line: "I took out his ID from the wallet. “His name is Alan,” the deputy continues. “19, always laughing according to the classmates who knew him.”<br/><br/>“How about the second body?” I asked. <br/><br/>“The second one had sustained a gunshot on the side of her cheek while the gun seemed to be touching her face. The second body also had bodily fluids “flowing out” of her.”",
    choice: false,
    goto: 10,
  },
  {
    id: 10,
    line: "“It’s pretty safe to say that the girl was the target then. Have you guys determined who it is?” I asked. <br/><br/>“Aileen, 21 years old, a student at this university. According to those who knew her, she was a very curious and nice person.” <br/><br/>Huh. Our country keeps failing to protect these children.",
    choice: false,
    goto: 11,
  },
  {
    id: 11,
    line: "The deputy continues without me prompting him. “I was thinking that maybe Alan did it.” <br/><br/>I put the wallet down on the table and raised an eyebrow. “Elaborate?”",
    choice: false,
    goto: 12,
  },
  {
    id: 12,
    line: "“Not trying to victim blame, of course. But from those same classmates, we heard that Alan got into a fight with another guy a couple months ago. Alan liked Aileen, but got rejected because Aileen has a boyfriend. He pretended to be understanding and continued being friends. Then when he lost the fight, his ego got hurt, and what do men with hurt ego do? They like to blame it on women, and Alan blamed it on Aileen because she rejected him. Therefore, I think it's pretty safe to say that Alan did it.”",
    choice: false,
    goto: 13,
  },
  {
    id: 13,
    line: "Wow. So he already has a theory.",
    choice: true,
    ca: "(A) His theory seems reasonable",
    cb: "(B) What is this kid saying?",
    gotoa: 14,
    gotob: 15,
  },
  {
    id: 14,
    line: 'Huh, seems reasonable. "Wrap up the case and call it a day".<br/><br/>But is that really the truth?',
    choice: false,
    goto: 0,
  },
  {
    id: 15,
    line: "If Allan was the culprit, <i>then how would he have shot himself from a 2-3 foot range?</i> Why would he shoot himself? This deputy is making a fool out of himself. I ordered the deputy to run a DNA test on Aileen’s body instead of agreeing with his nonsense. <br/><br/>Afterwards, I called the deputy, “Have everyone do a round check in the neighborhood,” I ordered, “Find potential witnesses for this case.”<br/><br/>“Allan couldn’t have done it,” I mutter, “Something isn’t adding up..”",
    choice: false,
    goto: 16,
  },
  {
    id: 16,
    line: "The next day, nothing had been discovered. I called the task force in for a meeting, taking a long sip of coffee before speaking, “I called you all in to talk about the matter on hand,” I pause to make sure everyone is focusing, “12,000 lives are at risk as we speak. Each day that the case remains unsolved, a student is under the threat of being murdered. I want you all to scrap the drug runner case, and focus on gathering all the evidence you can find.”",
    choice: false,
    goto: 17,
  },
  {
    id: 17,
    line: "One of my men interrupts before I speak again, “But what about the mayor?”<br/><br/>“I’ll worry about him, but for now I want each and every one of you to prioritize this case. Justice must be served to these students.”",
    choice: false,
    goto: 18,
  },
  {
    id: 18,
    line: "It was midday now. The only thing we had going for this case right now was the DNA test. I had little hope when an officer called, “Major, I was doing a round check on a house just now, and a civilian had found a bullet casing near the road where Allan’s body was found.” He handed the bullet casing over to me. <br/><br/>Though the bullet casing was not as useful, this was the only form of evidence that could keep this case on track. I passed the bullet casing to be tested.",
    choice: false,
    goto: 19,
  },
  {
    id: 19,
    line: "Just as I finished managing the bullet casing for testing, one of my fellow officers called me. “Major, Major! Officer Arbor is missing.”<br/><br/><i>...What</i>.",
    choice: true,
    ca: "(A) Search for the missing officer",
    cb: "(B) Worry about him later and put all effort into working on the murder case",
    gotoa: 20,
    gotob: 22,
  },
  {
    id: 20,
    line: "As I attempt to shift the focus onto finding the missing officer, the public gets annoyed. They do not like that I am attempting to even shift the resources from the case. They rioted every day in front of the police station, demanding that I get removed from my position of power. What should I do?",
    choice: true,
    ca: "(A) Continue searching for officer Arbor",
    cb: "(B) Public sentiment is more important: I will shift my focus onto the case.",
    gotoa: 21,
    gotob: 22,
  },
  {
    id: 21,
    line: "I decided to continue with my search for Officer Arbor. However, with the protests in front of the police station every day, the higher ups had decided to fire me.<br/><br/>I had failed these children.",
    choice: false,
    goto: 0,
  },
  {
    id: 22,
    line: "Although I decided to move forward with the case, the disappearance of the officer had alarmed us. The mayor’s house was close to where Allan’s body was found. What if the killers target him next?<br/><br/>The next day, I visited the mayor, informing him about my worries. “Sir, now that there are thousands of lives at risk, I am worried about your safety. You need to do something now, and get somewhere far away from here.” ",
    choice: false,
    goto: 23,
  },
  {
    id: 23,
    line: "The officer sipped his tea and smiled, straightening his signature white polo shirt. “It’s alright, major. I have faith in God's protection.”<br/><br/>“But mayor,” I say. <br/><br/>“I will pray to god,” he smiles, “I believe he will keep me safe,”",
    choice: true,
    ca: "(A) Prioritize the case",
    cb: "(B) Prioritize the mayor's safety",
    gotoa: 25,
    gotob: 24,
  },
  {
    id: 24,
    line: "The public was not happy with my decision. They are annoyed that I decided to put more effort into protecting a person of high power rather than protecting those who are vulnerable. They persistently protested in front of the police station every day requesting for me to be discharged. With time, my superiors had no choice but to accept their request.<br/><br/>I did things with the best intention, yet I was not able to bring these children to justice.",
    choice: false,
    goto: 0,
  },
  {
    id: 25,
    line: "I grimace, there’s no convincing this man. The mayor has always been a religious man at heart. Besides, there is a case that we need to solve. To bring justice, and save the lives of more citizens.<br/><br/>I meet with Khan, a potential culprit, who reportedly had a physical fight with Allan. He sits across from me, confused as to why he was in the station. ",
    choice: false,
    goto: 26,
  },
  {
    id: 26,
    line: "“I’m sorry for the sudden question”, he shifts in his seat, “but why was I called here?”<br/><br/>I slid a picture of Allan across the table to him, “Do you recognize this man? Perhaps someone you have gotten into a physical fight with?”<br/><br/>He nods, “Yeah, we did get into an argument, but that was months ago. We resolve our issues.”",
    choice: false,
    goto: 27,
  },
  {
    id: 27,
    line: "I raise my eyebrow, seeing the blood on his pants. I don’t buy it.  “If you two resolved your issues, why is there blood on your pants?” I question.<br/><br/>“Oh, this? I had punched a wall earlier, and blood had gotten onto my pants.”<br/><br/>I still didn’t buy it. After our meeting, I ordered the police force to continue looking into Khan’s story. Something about it had made me feel uneasy.",
    choice: false,
    goto: 28,
  },
  {
    id: 28,
    line: "However, after investigating his claim and Khan’s friends confirming that there wasn’t any rivalry between the two, we were at another dead end.<br/><br/>When I had thought all hope was lost, the deputy came in with the DNA tests. Handing it to me, the detective says, “the test reveals that seven men were involved with the bodily fluids and murder of Eileen.”",
    choice: false,
    goto: 29,
  },
  {
    id: 29,
    line: 'Wow, 7. How cruel do these people have to be to do that? <br/><br/> “But,” he continues, “the test led to no matches in the system meaning that the perpetrators had little to no involvement in crime beforehand. Additionally, we looked over the bullet casings that were found, and striations were found in it." <br/><br/>“Odd,” I frown, “How could the perpetrators have no criminal history despite the cruelty of this case?”',
    choice: false,
    goto: 30,
  },
  {
    id: 30,
    line: "After my meeting with the deputy, I ran the bullet case through a system of all the registered guns in the country. After a few minutes, the match was found, a M16 rifle with a serial number of 773159.<br/><br/>“What…” I frowned, “this can’t be right.”",
    choice: false,
    goto: 31,
  },
  {
    id: 31,
    line: "M16 was a standard police rifle in the Philippines and the serial number belonged to Officer Louis. But he had turned his gun in, so how could he have-? Huh, turned in on the day the bodies were discovered… <br/><br/> I suddenly heard something from the news that was playing from the TV in the back. “...with the rise of this case, the public, especially university students, have been uneasy. By gathering and interviewing neighbors, they were able to make a composite sketch of the driver of the van.”",
    choice: false,
    goto: 32,
  },
  {
    id: 32,
    line: "I snapped my head and looked at the TV. Then I did a double take, closed my eyes, and opened them again, only to see the same face.<br/><br/>The sketch looked exactly like Officer Arbor.",
    choice: true,
    ca: "(A) I have been betrayed by my own men!",
    cb: "(B) This is all just a bad coincidence...",
    gotoa: 34,
    gotob: 33,
  },
];
